### ISSUE TITLE
Trigger email after applicants complete registration to alert about Job picker site

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#52] opened 2017-03-24 19:56 UTC
Send an email to youth who have completed an application.

**Comment by mzagaja** [comment] 2017-03-24 20:36
Waiting on Deron to provide e-mail text and information on who it is from.

**Comment by mzagaja** [comment] 2017-03-24 20:57
Closing as duplicate of #37.

**Closed by mzagaja** 2017-03-24 20:57 UTC
