### ISSUE TITLE
Jobs on map should be filtered by applicants' chosen job categories

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#38] opened 2017-03-20 15:53 UTC
When applicant opens "job picker" interface, they view jobs on a map associated with their job category preference. (From Applicant Data)

**Comment by allthesignals** [comment] 2017-03-22 14:41
Isn't this a duplicate of #40?

**Comment by mzagaja** [comment] 2017-03-24 13:31
Agree, going to close this in favor of #40 because even though this one came first, the new one is more descriptive.

**Closed by mzagaja** 2017-03-24 13:31 UTC
Labels: enhancement
